name: Update Filters
on:
  push:
    paths-ignore:
      - 'README.md'
      - '*.md'
    branches: [ main ]
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  Update_Filters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          path: release
          ref: release

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/main
          mvn -B package

      - name: Run Jar
        env:
          DOMAIN_EXCLUDE: ${{ vars.DOMAIN_EXCLUDE }}
        run: |
          cd ${{ github.workspace }}/main
          java -jar ./target/adg-rule-1.0.0.jar
      
      - name: Prepare
        run: |
          cd ${{ github.workspace }}/release
          git reset --hard 9dc2293efb4c49d4a6a53a22c34b61bbc99feaff
          mkdir rule
          mv ${{ github.workspace }}/main/rule/* ${{ github.workspace }}/release/rule/
          git add .
          git commit -m "CI Updated at $(date +'%Y-%m-%d %H:%M:%S')" -a
      
      - name: Release rules
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: ${{ github.workspace }}/release
          branch: release
          force_with_lease: true

      - name: Mirror Refresh
        run: sleep 10 && curl 'https://purge.jsdelivr.net/gh/${{github.repository}}@release/rule'


      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
